xo/urls.py
from django.urls import path

from . import views

app_name = 'xo'
urlpatterns = [
    path('', views.index, name='index'),
    path('game/<int:pk>/', views.game, name='game'),
    path('ajax/board_update/', views.board_update, name='board_update'),
]

xosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('xo.urls')),
    path('admin/', admin.site.urls),
]

xo/models.py
from django.db import models
from django.shortcuts import reverse


from .players import get_player
from . import board_utils
from xo.board_utils import Move
from xo.utils import make_logger


logger = make_logger('models.py')


MARKER_X = 'X'
MARKER_O = 'O'


class Game(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    # goes up to 2^31 - 1, so 5x5 has 25 cells is still ok
    board_x = models.PositiveIntegerField(default=0)
    board_o = models.PositiveIntegerField(default=0)

    player_x = models.CharField(max_length=64)
    player_o = models.CharField(max_length=64)

    n_rows = models.IntegerField(default=3)
    n_cols = models.IntegerField(default=3)
    n_connects = models.IntegerField(default=3)
    is_kriegspiel = models.BooleanField(default=False)

    def __repr__(self):
        repr_ = 'Game({}, {}, {}, "{}")'
        repr_ = repr_.format(self.n_rows, 
                             self.n_cols, 
                             self.n_connects,
                             self.board_str)
        return repr_

    def __str__(self):
        return str(repr(self))

    def get_absolute_url(self):
        return reverse('xo:game', kwargs={'pk': self.pk})

    @property
    def empty_indexes(self):
        return board_utils.get_empty_indexes(
            self.board_x, self.board_o, self.n_cells)

    @property
    def n_cells(self):
        return self.n_rows * self.n_cols

    @property
    def board_str(self):
        return board_utils.get_board_str(
            self.board_x, self.board_o, self.n_cells)

    @property
    def board_mat(self):
        mat = board_utils.get_board_mat(
            self.board_x, self.board_o, self.n_rows, self.n_cols)
        
        info_msg = '({}x{}) board mat: \n{}'
        info_msg = info_msg.format(self.n_rows, self.n_cols, mat)
        logger.info(info_msg)

        return mat

    @property
    def full_state(self):
        return (1 << self.n_cells) - 1

    @property
    def is_filled(self):
        return board_utils.is_filled(
            self.board_x, self.board_o, self.full_state)

    @property
    def next_player(self):
        return board_utils.get_next_player(
            self.board_x, self.board_o, self.n_cells)

    @property
    def cur_player(self):
        return board_utils.get_cur_player(
            self.board_x, self.board_o, self.n_cells)

    @property
    def cur_player_type(self):
        if self.cur_player == board_utils.MARKER_O:
            return self.player_o
        else:
            return self.player_x

    @property
    def next_player_type(self):
        if self.next_player == board_utils.MARKER_O:
            return self.player_o
        else:
            return self.player_x

    def is_next_player_human(self):
        if self.next_player == board_utils.MARKER_O:
            return self.player_o == 'human'
        else:
            return self.player_x == 'human'

    @property
    def is_game_over(self):
        is_over =  board_utils.is_game_over(
            self.board_x, self.board_o, self.n_rows, self.n_cols, self.n_connects)
        # print('Game {} is over: {}'.format(self.pk, is_over))
        return is_over

    def is_empty(self, index):
        return board_utils.is_empty(
            self.board_x, self.board_o, index)

    def add_cross(self, index):
        flag = 1 << index
        self.board_x |= flag

    def add_circle(self, index):
        flag = 1 << index 
        self.board_o |= flag

    def play_auto(self):
        if self.is_game_over:
            return 

        has_human = self.player_x == 'human' or self.player_o == 'human'

        if has_human:
            next_player = self.next_player
            player = self.player_x if next_player == MARKER_X else self.player_o

            if player == 'human':
                return 

            player_obj = get_player(player)
            self.play(player_obj.play(self))
        else:
            while not self.is_game_over:
                next_player = self.next_player
                player = self.player_x if next_player  == MARKER_X else self.player_o
                player_obj = get_player(player)
                self.play(player_obj.play(self))

    def play_next_auto(self):
        # play next auto move if possible
        if self.is_game_over:
            err_msg = 'Cannot play next move for a game that has ended'
            raise ValueError(err_msg)

        if self.next_player_type == 'human':
            return None

        next_player = self.next_player
        player = self.player_x if next_player == MARKER_X else self.player_o
        # info_msg = 'Get player {}'.format(player)
        # logger.info(info_msg)
        player_obj = get_player(player)
        # info_msg = 'Got player {}'.format(player_obj)
        # logger.info(info_msg)
        index = player_obj.play(self)
        self.play(index)

        row_ind = index // self.n_cols
        col_ind = index % self.n_cols
        move = {
            'row_ind': row_ind,
            'col_ind': col_ind,
            'marker': next_player,
        }

        return move

    def play_xy(self, row_ind, col_ind):
        index = row_ind * self.n_cols + col_ind
        self.play(index)

    def play(self, index):
        info_msg = 'Player {} playing index {} at game {}'
        info_msg = info_msg.format(self.next_player, index, self.pk)
        print(info_msg)

        if index < 0 or index >= self.n_cells:
            err_msg = 'Invalid board index {} not in [{}, {})'
            err_msg = err_msg.format(index, 0, self.n_cells)
            raise IndexError(err_msg)

        if not self.is_empty(index):
            err_msg = 'Cell is not empty at index {}'
            err_msg = err_msg.format(index)
            raise ValueError(err_msg)

        if self.next_player == MARKER_X:
            self.add_cross(index)
        else:
            self.add_circle(index)


class BoardState(models.Model):
    """All the board state is cached with their utility value assuming that it is at a max layer
    """
    # goes up to 2^31 - 1, so 5x5 has 25 cells is still ok
    board_x = models.PositiveIntegerField(default=0)
    board_o = models.PositiveIntegerField(default=0)

    n_rows = models.IntegerField(default=3)
    n_cols = models.IntegerField(default=3)
    n_connects = models.IntegerField(default=3)

    depth = models.IntegerField(default=0)
    flag = models.IntegerField(default=board_utils.EXACT)
    value = models.IntegerField()

    def __repr__(self):
        repr_ = 'BoardState({}, {}, {}, "{}", {}, {}, {})'
        flag_str = board_utils.flag2str(self.flag)
        repr_ = repr_.format(self.n_rows, 
                             self.n_cols,
                             self.n_connects,
                             self.board_str,
                             self.depth,
                             self.value,
                             flag_str)
        return repr_

    def __str__(self):
        return str(repr(self))

    @property
    def board_str(self):
        s = ''
        for i in range(self.n_cells):
            v = ' '
            flag = 1 << i
            has_x = self.board_x & flag
            has_o = self.board_o & flag
            if has_x:
                v = MARKER_X
            if has_o:
                v = MARKER_O
            s += v
        return s

    @classmethod
    def cache(cls, board_x, board_o, n_rows, n_cols, n_connects, depth, value, flag):
        # cache if it's not already there
        results = BoardState.objects.filter(
            n_rows__exact=n_rows,
            n_cols__exact=n_cols,
            n_connects__exact=n_connects,
            board_x__exact=board_x,
            board_o__exact=board_o,
            flag__exact=flag,
            depth__gte=depth,
        )

        if len(results):
            return
        
        BoardState.objects.create(
            board_x=board_x,
            board_o=board_o,
            n_rows=n_rows,
            n_cols=n_cols,
            n_connects=n_connects,
            flag=flag,
            value=value,
            depth=depth,
        )

    @classmethod
    def get_cache(cls, board_x, board_o, n_rows, n_cols, n_connects):
        cache = None
        results = BoardState.objects.filter(
            n_rows__exact=n_rows,
            n_cols__exact=n_cols,
            n_connects__exact=n_connects,
            board_x__exact=board_x,
            board_o__exact=board_o,
        ).order_by('flag', '-depth')
        len_ = len(results)
        if len_ > 0:

            # info_msg = 'Number of cached states: {}'.format(len_)
            # logger.info(info_msg)

            cache = results[0]
            results.delete()

        return cache

xo/forms.py
import random

from django import forms
from django.core.exceptions import ImproperlyConfigured, ValidationError

from .models import Game, BoardState
from .players import get_player


def validate_player_type(player_type):
    if player_type == 'human':
        return True
    try:
        return get_player(player_type) is not None
    except (ImproperlyConfigured, ImportError):
        err_msg = 'Unknown player type: {}'.format(player_type)
        print('Validation error: {}'.format(err_msg))
        raise ValidationError(err_msg)


PLAYER_TYPES = [
    ('human', 'Human'),
    ('xo.players.RandomPlayer', 'Random player'),
    ('xo.players.MinimaxPlayer', 'Minimax player'),
    ('xo.players.MCTSPlayer', 'MCTS player'),

]


class NewGameForm(forms.Form):
    is_kriegspiel = forms.BooleanField(required=False)
    n_rows = forms.IntegerField(initial=3, min_value=3, max_value=5)
    n_cols = forms.IntegerField(initial=3, min_value=3, max_value=5)
    n_connects = forms.IntegerField(initial=3, min_value=3, max_value=5)
    player_x = forms.CharField(widget=forms.Select(choices=PLAYER_TYPES))
    player_o = forms.CharField(widget=forms.Select(choices=PLAYER_TYPES[::-1]))

    def create(self):
        players = [
            self.cleaned_data['player_x'], 
            self.cleaned_data['player_o'],
        ]
        return Game.objects.create(
            player_x=players[0],
            player_o=players[1],
            board_x=0,
            board_o=0,
            n_rows=self.cleaned_data['n_rows'],
            n_cols=self.cleaned_data['n_cols'],
            n_connects=self.cleaned_data['n_connects'],
            is_kriegspiel=self.cleaned_data['is_kriegspiel']
        )

    def clean(self):
        cleaned_data = super().clean()
        n_rows = cleaned_data['n_rows']
        n_cols = cleaned_data['n_cols']
        n_connects = cleaned_data['n_connects']
        player_x = cleaned_data['player_x']
        player_o = cleaned_data['player_o']

        # check that n_connects is valid
        max_dim = max(n_rows, n_cols)
        if n_connects > max_dim:
            err_msg = 'No. of connects: {} to win cannot be larger than maximum dimension: {}'
            err_msg = err_msg.format(n_connects, max_dim)
            raise ValidationError(
                err_msg,
                code='invalid'
            )

#         if player_x != 'human' and player_o != 'human':
#             err_msg = 'Not supporting two AI playing yet.'
#             raise ValidationError(
#                 err_msg,
#                 code='invalid'
#             )
 

class MoveForm(forms.Form):
    row_index = forms.IntegerField(min_value=0)
    col_index = forms.IntegerField(min_value=0)

xo/views.py
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import ensure_csrf_cookie
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse


from .forms import NewGameForm, MoveForm
from .models import Game
from .utils import make_logger
from xo.board_utils import MARKER_O, MARKER_X


logger = make_logger('views.py')


@require_http_methods(['GET', 'POST'])
def index(request):
    if request.method == 'POST':
        form = NewGameForm(request.POST)
        if form.is_valid():
            game = form.create()
            game.save()
            url = game.get_absolute_url()
            print('Redirect to {}'.format(url))
            return redirect(game)
    else:
        form = NewGameForm()
    return render(request, 'xo/new_game.html', {'form': form})


def get_board_html(n_rows, n_cols):
    if n_rows == 3 and n_cols == 3:
        html = 'xo/3x3.html'
    elif n_rows == 4 and n_cols == 4:
        html = 'xo/4x4.html'
    elif n_rows == 5 and n_cols == 5:
        html = 'xo/5x5.html'
    else:
        err_msg = 'Do not have html for dimension: ({}, {})'
        err_msg = err_msg.format(n_rows, n_cols)
        raise ValueError(err_msg)
    info_msg = 'Getting board ({}x{}) html: {}'
    info_msg = info_msg.format(n_rows, n_cols, html)
    print(info_msg)
    return html


@require_http_methods(['GET', 'POST'])
def game(request, pk):
    info_msg = 'Game request method: {} for game {}'
    info_msg = info_msg.format(request.method, pk)
    print(info_msg)
    game = get_object_or_404(Game, pk=pk)
    if request.method == 'POST':
        form = MoveForm(request.POST)
        if form.is_valid():
            if game.is_next_player_human():
                row_ind = form.cleaned_data['row_index']
                col_ind = form.cleaned_data['col_index']
                game.play_xy(row_ind, col_ind)
                game.save()
            return redirect(game)
        else:
            err_msg = 'MoveForm invalid, should not happen'
            raise ValueError(err_msg)
    else:
        # game.play_auto()
        game.save()

    board_width = (game.n_cols + 1) * 90 - 10
    print('Board width: {}'.format(board_width))

    # html = get_board_html(game.n_rows, game.n_cols)
    html = 'xo/nxn.html'
    context = {
        'game': game,
        'board_width': board_width,
    }
    return render(request, html, context)


@ensure_csrf_cookie
def board_update(request):
    info_msg = 'Board update view function called'
    logger.info(info_msg)

    # get info
    game_id = request.GET.get('game_id', -1)
    row_ind = int(request.GET.get('row_index', -1))
    col_ind = int(request.GET.get('col_index', -1))
    player = request.GET.get('next_player', None)

    info_msg = 'Game {}: cell ({}, {}) marked with {}'
    info_msg = info_msg.format(game_id,
                               row_ind, col_ind,
                               player)
    logger.info(info_msg)

    # update game state
    game = get_object_or_404(Game, pk=game_id)
    if not (row_ind == -1 or col_ind == -1):
        game.play_xy(row_ind, col_ind)

    try:
        move = game.play_next_auto()
    except:
        move = None
    game.save()

    # make message
    if game.is_game_over == MARKER_X:
        msg = 'Player X wins!'
    elif game.is_game_over == MARKER_O:
        msg = 'Player O wins!'
    elif game.is_game_over == ' ':
        msg = 'Game drawn.'
    else:
        msg = "Player {}'s turn"
        msg = msg.format(game.next_player)

    data = {
        'message': msg,
        'move': move,
        'is_game_over': game.is_game_over,
        'game_id': game_id,
        'next_player': game.next_player,
        'next_player_type': game.next_player_type,
    }
    info_msg = 'JSON response: ' + str(data)
    logger.info(info_msg)
    return JsonResponse(data)


def board_3x3(request):
    context = {}
    return render(request, 'xo/3x3.html', context)


def board_4x4(request):
    context = {}
    return render(request, 'xo/4x4.html', context)

xo/templates/xo/3x3.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'xo/main.css' %}">

<body>
    {% with next_player=game.next_player game_over=game.is_game_over %}
        <div class="text-center" id="box-3x3">
            <header>
                <h1>3 x 3 board</h1>
            </header>
            {% if game_over == 'X' %}
                <div id="message">
                    <div>Player X wins!</div>
                    <a href="{% url 'xo:index' %}" id="message">Start a new game.</a>
                </div>
            {% elif game_over == 'O' %}
                <div id="message">
                    <div>Player O wins!</div>
                    <a href="{% url 'xo:index' %}" id="message">Start a new game.</a>
                </div>
            {% elif game_over == ' ' %}
                <div id="message">
                    <div>Game drawn.</div>
                    <a href="{% url 'xo:index' %}" id="message">Start a new game.</a>
                </div>
            {% else %}
                <div id="message">Player {{ next_player }}'s turn</div>
            {% endif %}
            <div class="board">
                <div>
                    {% include "includes/square.html" with game=game index=0 value=game.board_str.0 %}
                    {% include "includes/square.html" with game=game index=1 value=game.board_str.1 %}
                    {% include "includes/square.html" with game=game index=2 value=game.board_str.2 %}
                </div>
                <div>
                    {% include "includes/square.html" with game=game index=3 value=game.board_str.3 %}
                    {% include "includes/square.html" with game=game index=4 value=game.board_str.4 %}
                    {% include "includes/square.html" with game=game index=5 value=game.board_str.5 %}
                </div>
                <div>
                    {% include "includes/square.html" with game=game index=6 value=game.board_str.6 %}
                    {% include "includes/square.html" with game=game index=7 value=game.board_str.7 %}
                    {% include "includes/square.html" with game=game index=8 value=game.board_str.8 %}
                </div>
            </div>
        </div>
    {% endwith %}
</body>

xo/templates/xo/4x4.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'xo/main.css' %}">

<body>
    {% with next_player=game.next_player game_over=game.is_game_over %}
        <div class="text-center" id="box-4x4">
            <header>
                <h1>4 x 4 board</h1>
            </header>
            {% if game_over == 'X' %}
                <div id="message">
                    <div>Player X wins!</div>
                    <a href="{% url 'xo:index' %}" id="message">Start a new game.</a>
                </div>
            {% elif game_over == 'O' %}
                <div id="message">
                    <div>Player O wins!</div>
                    <a href="{% url 'xo:index' %}" id="message">Start a new game.</a>
                </div>
            {% elif game_over == ' ' %}
                <div id="message">
                    <div>Game drawn.</div>
                    <a href="{% url 'xo:index' %}" id="message">Start a new game.</a>
                </div>
            {% else %}
                <div id="message">Player {{ next_player }}'s turn</div>
            {% endif %}
            <div class="board">
                <div>
                    {% include "includes/square.html" with game=game index=0 value=game.board_str.0 %}
                    {% include "includes/square.html" with game=game index=1 value=game.board_str.1 %}
                    {% include "includes/square.html" with game=game index=2 value=game.board_str.2 %}
                    {% include "includes/square.html" with game=game index=3 value=game.board_str.3 %}
                </div>
                <div>
                    {% include "includes/square.html" with game=game index=4 value=game.board_str.4 %}
                    {% include "includes/square.html" with game=game index=5 value=game.board_str.5 %}
                    {% include "includes/square.html" with game=game index=6 value=game.board_str.6 %}
                    {% include "includes/square.html" with game=game index=7 value=game.board_str.7 %}
                </div>
                <div>
                    {% include "includes/square.html" with game=game index=8 value=game.board_str.8 %}
                    {% include "includes/square.html" with game=game index=9 value=game.board_str.9 %}
                    {% include "includes/square.html" with game=game index=10 value=game.board_str.10 %}
                    {% include "includes/square.html" with game=game index=11 value=game.board_str.11 %}
                </div>
                <div>
                    {% include "includes/square.html" with game=game index=12 value=game.board_str.12 %}
                    {% include "includes/square.html" with game=game index=13 value=game.board_str.13 %}
                    {% include "includes/square.html" with game=game index=14 value=game.board_str.14 %}
                    {% include "includes/square.html" with game=game index=15 value=game.board_str.15 %}
                </div>
            </div>
        </div>
    {% endwith %}
</body>

xo/templates/xo/5x5.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'xo/main.css' %}">

<body>
    {% with next_player=game.next_player game_over=game.is_game_over %}
        <div class="text-center" id="box-5x5">
            <header>
                <h1>{{ game.n_rows }} x {{ game.n_cols }} board</h1>
            </header>
            {% if game_over == 'X' %}
                <div id="message">
                    <div>Player X wins!</div>
                    <a href="{% url 'xo:index' %}" id="message">Start a new game.</a>
                </div>
            {% elif game_over == 'O' %}
                <div id="message">
                    <div>Player O wins!</div>
                    <a href="{% url 'xo:index' %}" id="message">Start a new game.</a>
                </div>
            {% elif game_over == ' ' %}
                <div id="message">
                    <div>Game drawn.</div>
                    <a href="{% url 'xo:index' %}" id="message">Start a new game.</a>
                </div>
            {% else %}
                <div id="message">Player {{ next_player }}'s turn</div>
            {% endif %}
            <div class="board">
                <div>
                    {% include "includes/square.html" with game=game index=0 value=game.board_str.0 %}
                    {% include "includes/square.html" with game=game index=1 value=game.board_str.1 %}
                    {% include "includes/square.html" with game=game index=2 value=game.board_str.2 %}
                    {% include "includes/square.html" with game=game index=3 value=game.board_str.3 %}
                    {% include "includes/square.html" with game=game index=4 value=game.board_str.4 %}
                </div>
                <div>
                    {% include "includes/square.html" with game=game index=5 value=game.board_str.5 %}
                    {% include "includes/square.html" with game=game index=6 value=game.board_str.6 %}
                    {% include "includes/square.html" with game=game index=7 value=game.board_str.7 %}
                    {% include "includes/square.html" with game=game index=8 value=game.board_str.8 %}
                    {% include "includes/square.html" with game=game index=9 value=game.board_str.9 %}
                </div>
                <div>
                    {% include "includes/square.html" with game=game index=10 value=game.board_str.10 %}
                    {% include "includes/square.html" with game=game index=11 value=game.board_str.11 %}
                    {% include "includes/square.html" with game=game index=12 value=game.board_str.12 %}
                    {% include "includes/square.html" with game=game index=13 value=game.board_str.13 %}
                    {% include "includes/square.html" with game=game index=14 value=game.board_str.14 %}
                </div>
                <div>
                    {% include "includes/square.html" with game=game index=15 value=game.board_str.15 %}
                    {% include "includes/square.html" with game=game index=16 value=game.board_str.16 %}
                    {% include "includes/square.html" with game=game index=17 value=game.board_str.17 %}
                    {% include "includes/square.html" with game=game index=18 value=game.board_str.18 %}
                    {% include "includes/square.html" with game=game index=19 value=game.board_str.19 %}
                </div>
                <div>
                    {% include "includes/square.html" with game=game index=20 value=game.board_str.20 %}
                    {% include "includes/square.html" with game=game index=21 value=game.board_str.21 %}
                    {% include "includes/square.html" with game=game index=22 value=game.board_str.22 %}
                    {% include "includes/square.html" with game=game index=23 value=game.board_str.23 %}
                    {% include "includes/square.html" with game=game index=24 value=game.board_str.24 %}
                </div>
            </div>
        </div>
    {% endwith %}
</body>

xo/templates/xo/new_game.html
{% extends 'base.html' %}

{% block stylesheet %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'xo/new_game.css' %}">
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col">
        <form method="POST" id="box">
            <h1>Tic Tac Toe</h1>
            <hr class="mt-0 mb-4">
            {% csrf_token %}
            <div class="form-group">
                <label class="label">Number of rows</label>
                {{ form.n_rows }}
            </div>
            <div class="form-group">
                <label class="label">Number of columns</label>
                {{ form.n_cols }}
            </div>
            <div class="form-group">
                <label class="label">Number of connects</label>
                {{ form.n_connects }}
            </div>
            <div class="form-group">
                <label class="label">Player X type</label>
                {{ form.player_x }}
            </div>
            <div class="form-group">
                <label class="label">Player O type</label>
                {{ form.player_o }}
            </div>
            <button type="submit">Play</button>
        </form>
    </div>
</div>
{% endblock %}

xo/templates/xo/nxn.html
{% extends 'base.html' %}

{% block stylesheet %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'xo/main.css' %}">
{% endblock %}

{% block content %}
    {% with next_player=game.next_player next_player_type=game.next_player_type game_over=game.is_game_over %}
    <div class="row justify-content-center">
        <div class="col-sm-auto row-width row-height board" id="board" next-player="{{ next_player }}" next-player-type="{{ next_player_type }}" board-update-url="{% url 'xo:board_update' %}" game-id={{ game.id }} new-game-url="{% url 'xo:index' %}">
        <div class="row justify-content-center">
            <h1>{{ game.n_rows }} x {{ game.n_cols }} board</h1>
        </div>
        <hr class="mt-0 mb-4">
        <div class="row">
            <div class="col" id="message">
            {% if game_over == 'X' %}
                <div class="row justify-content-center">Player X wins!</div>
                <a href="{% url 'xo:index' %}" class="row justify-content-center" id="message-link">Start a new game.</a>
            {% elif game_over == 'O' %}
                <div>Player O wins!</div>
                <a href="{% url 'xo:index' %}">Start a new game.</a>
            {% elif game_over == ' ' %}
                <div>Game drawn.</div>
                <a href="{% url 'xo:index' %}">Start a new game.</a>
            {% else %}
                <div>Player {{ next_player }}'s turn</div>
            {% endif %}
            </div>
        </div>
        <div class="row justify-content-center">
            <table class="table table-borderless table-fit">
                {% for row in game.board_mat %}
                <tr id="{{ forloop.counter0 }}">
                        {% for value in row %}
                        <td row-ind={{ forloop.parentloop.counter0 }} col-ind={{ forloop.counter0 }}>
                            {% include "includes/square1.html" with game=game row_index=forloop.parentloop.counter0 col_index=forloop.counter0 value=value %}
                            </td>
                        {% endfor %}
                </tr>
                {% endfor %}
            </table>
        </div>
        </div>
    </div>
    {% endwith %}
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/game.js' %}"></script>
{% endblock %}